/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MaterialsManager;

import Business.Enterprise.Enterprise;
import Business.Organization.MaterialAdminOrganization;
import Business.Stakeholders.Kit;
import Business.Stakeholders.KitDirectory;
import Business.Stakeholders.Patients;
import Business.Stakeholders.Visits;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.CRCAdminRole.CRCAdminManageStudyPanel;
import Business.Enterprise.ClinicalLabEnterprise;
import Business.Stakeholders.studies;
import Business.Stakeholders.studiesDirectory;

/**
 *
 * @author Gaurav
 */
public class AddKitPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddKitPanel
     */
    
    JPanel userProcessContainer;
//    UserAccount account;
//    DoctorOrganization doctorOrganization;
    Enterprise enterprise;
    Kit kit;
    KitDirectory kitDirectory;
    ClinicalLabEnterprise clinicalLabEnterprise; 
studiesDirectory studiesdirectory;

    AddKitPanel(JPanel userProcessContainer, studiesDirectory studiesdirectory,  Enterprise enterprise) {
      initComponents();
      this.userProcessContainer=userProcessContainer;
//      this.kitDirectory = kitDirectory;
      this.clinicalLabEnterprise = (ClinicalLabEnterprise)enterprise;
      this.studiesdirectory = studiesdirectory;
      
      
      
      studyComboBox1.removeAllItems();
       for(studies s : studiesdirectory.getStudyList()) {
//           System.out.println("Studies Loop ===>  "+s.getIrbID());
           studyComboBox1.addItem(s);
       }
      
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKitLabel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKitBarcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKitItems = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKitLocation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inStockcombo = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        expiryDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        studyComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B&W Site Admin/CRC");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 270, 29));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Kit Label");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, 30));

        txtKitLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtKitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 173, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Kit Barcode");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, 30));

        txtKitBarcode.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtKitBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 173, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Kit Items");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 110, 30));

        txtKitItems.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtKitItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 173, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Kit Expiry Date");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 180, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Kit Location");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 140, 30));

        txtKitLocation.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtKitLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 173, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Kit Status");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 140, 33));

        inStockcombo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        inStockcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "In-Stock", "Used", "Expired" }));
        inStockcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inStockcomboActionPerformed(evt);
            }
        });
        add(inStockcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 173, 33));

        btnSubmit.setBackground(new java.awt.Color(18, 51, 105));
        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 130, 50));

        btnBack.setBackground(new java.awt.Color(18, 51, 105));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 120, 50));
        add(expiryDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 180, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Select Study:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, 30));

        studyComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        studyComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(studyComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 161, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
       
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageKitPanel manageKitPanel = (ManageKitPanel) component;
        manageKitPanel.populate();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
//        userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        studies study = (studies)studyComboBox1.getSelectedItem();
        if(txtKitLabel.getText().isEmpty() || txtKitBarcode.getText().isEmpty() || txtKitItems.getText().isEmpty() || txtKitLocation.getText().isEmpty()
                || expiryDateChooser.getDate() == null)
        {
            JOptionPane.showMessageDialog(null,"Enter all the values!");
        }
        else{
//        Kit k = this.kitDirectory.addKit();
                Kit k = study.getKitdirectory().addKit();

//        k.setStudy(study.getStudyTitle());
        k.setKitLabel(txtKitLabel.getText());
        k.setKitBarcode(txtKitBarcode.getText());
        k.setKitItems(txtKitItems.getText());
        k.setKexpiryDate(expiryDateChooser.getDate());
        k.setKitLocation(txtKitLocation.getText());
        k.setKitStatus((String) inStockcombo.getSelectedItem());
        
        JOptionPane.showMessageDialog(null,"Kit Added Successfully!");
        txtKitLabel.setText("");
        txtKitBarcode.setText("");
        txtKitItems.setText("");
        txtKitLocation.setText("");
        expiryDateChooser.setDate(null);
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void inStockcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inStockcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inStockcomboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private com.toedter.calendar.JDateChooser expiryDateChooser;
    private javax.swing.JComboBox inStockcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox studyComboBox1;
    private javax.swing.JTextField txtKitBarcode;
    private javax.swing.JTextField txtKitItems;
    private javax.swing.JTextField txtKitLabel;
    private javax.swing.JTextField txtKitLocation;
    // End of variables declaration//GEN-END:variables
}
