/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MaterialsManager;

import Business.Stakeholders.Kit;
import Business.Stakeholders.KitDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Gaurav
 */
public class ViewKitPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewKitPanel
     */
    JPanel userProcessContainer;
    KitDirectory kitDirectory; 
    Kit kit;
    boolean flag;

    ViewKitPanel(JPanel userProcessContainer, KitDirectory kitDirectory, Kit kit, boolean flag) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.kitDirectory = kitDirectory;
        this.kit = kit;
        this.flag = flag;
        showData();
        if(flag == true)
        {
            updateStatus();
        }
    }
    
    void showData(){
        
        txtKitLabel.setText(kit.getKitLabel());
        txtKitBarcode.setText(kit.getKitBarcode());
        txtKitItems.setText(kit.getKitItems());
        txtLocation.setText(kit.getKitLocation());
        expiryDateChooser.setDate(kit.getKexpiryDate());
        statusComboBox.setSelectedItem(kit.getKitStatus());
        
    }
    
    void updateStatus(){
        
        txtKitLabel.setEnabled(false);
        txtKitBarcode.setEnabled(false);
        txtKitItems.setEnabled(false);
        txtLocation.setEnabled(false);
        expiryDateChooser.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKitLabel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKitBarcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKitItems = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        expiryDateChooser = new com.toedter.calendar.JDateChooser();
        statusComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B&W Site Admin/CRC");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 300, 24));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Kit Label");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 120, 28));

        txtKitLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtKitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 186, 28));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Kit Barcode");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, 28));

        txtKitBarcode.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtKitBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 186, 28));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Kit Items");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, 28));

        txtKitItems.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtKitItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 186, 28));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Kit Expiry Date");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 180, 28));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Kit Location");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 150, 28));

        txtLocation.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 186, 28));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Kit Status");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 120, 28));

        btnUpdate.setBackground(new java.awt.Color(18, 51, 105));
        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 150, 50));

        btnBack.setBackground(new java.awt.Color(18, 51, 105));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 140, 50));
        add(expiryDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 186, 28));

        statusComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "In Stock", "Used", "Expired" }));
        add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 186, 28));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel8.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel8.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageKitPanel manageKitPanel = (ManageKitPanel) component;
        manageKitPanel.populate();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
//        userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
                if(txtKitLabel.getText().isEmpty() || txtKitBarcode.getText().isEmpty() || txtKitItems.getText().isEmpty() || txtLocation.getText().isEmpty()
                || expiryDateChooser.getDate() == null)
        {
            JOptionPane.showMessageDialog(null,"Enter all the values!");
        }
        else{
        kit.setKitLabel(txtKitLabel.getText());
        kit.setKitBarcode(txtKitBarcode.getText());
        kit.setKitItems(txtKitItems.getText());
        kit.setKexpiryDate(expiryDateChooser.getDate());
        kit.setKitLocation(txtLocation.getText());
        kit.setKitStatus((String) statusComboBox.getSelectedItem());
        
        JOptionPane.showMessageDialog(null,"Kit Added Successfully!");
        txtKitLabel.setText("");
        txtKitBarcode.setText("");
        txtKitItems.setText("");
        txtLocation.setText("");
        expiryDateChooser.setDate(null);
        } 
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JDateChooser expiryDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox statusComboBox;
    private javax.swing.JTextField txtKitBarcode;
    private javax.swing.JTextField txtKitItems;
    private javax.swing.JTextField txtKitLabel;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
