/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CentralRepositoryAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
//import Business.Enterprise.MaterialEnterprise;
import Business.Enterprise.CentralRepositoryEnterprise;

/**
 *
 * @author harish
 */
public class CentralRepoAdminWorkArea extends javax.swing.JPanel {
    private Enterprise enterprise;
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount account;
//MaterialEnterprise materialEnterprise;
CentralRepositoryEnterprise centralRepositoryEnterprise;
    /**
     * Creates new form CentralRepoAdminWorkArea
     */
//    public CentralRepoAdminWorkArea() {
//        initComponents();
//    }

    public CentralRepoAdminWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, CentralRepositoryEnterprise enterprise, EcoSystem business) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
            initComponents();
            this.enterprise = enterprise;
            this.userProcessContainer=userProcessContainer;
            this.business = business;
            this.centralRepositoryEnterprise = enterprise;
            this.account = account;
            enterpriseNameLabel.setText(enterprise.getName());
            
            

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        enterpriseNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(18, 51, 105));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Manage Specimen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 248, 380, 50));

        jButton2.setBackground(new java.awt.Color(18, 51, 105));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Manage Speciment Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 380, 50));

        enterpriseNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        enterpriseNameLabel.setText("jLabel1");
        add(enterpriseNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel1.setBackground(new java.awt.Color(18, 51, 105));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
              ManageSpecimenJPanel manageSanapecimenJPanel = new ManageSpecimenJPanel(userProcessContainer,business,centralRepositoryEnterprise);
//           LabtechnicianCollectspecimen labtechnicianCollectspecimen = new LabtechnicianCollectspecimen(userProcessContainer, labOrganization, studiesdirectory, patientsDirectory, specimenTypeDirectory);
        userProcessContainer.add("ManageSpecimenJPanel", manageSanapecimenJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
               ManageSpecimenRequestJPanel manageSpecimenRequestJPanel = new ManageSpecimenRequestJPanel(userProcessContainer,business,centralRepositoryEnterprise,account);
//           LabtechnicianCollectspecimen labtechnicianCollectspecimen = new LabtechnicianCollectspecimen(userProcessContainer, labOrganization, studiesdirectory, patientsDirectory, specimenTypeDirectory);
        userProcessContainer.add("ManageSpecimenRequestJPanel", manageSpecimenRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
