/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabTechnicianRole;

import Business.Stakeholders.Patients;
import Business.Stakeholders.Specimen;
import Business.Stakeholders.SpecimenTypeDirectory;
import Business.Stakeholders.SpecimenTypes;
import Business.Stakeholders.Visits;
import Business.Stakeholders.studies;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.CRCAdminRole.CRCAdminManageStudyPanel;

/**
 *
 * @author shubh
 */
public class LabtechnicianAddspecimen extends javax.swing.JPanel {

    /**
     * Creates new form labtechnician_workarea_addspecimen
     */
    JPanel userProcessContainer;
    Visits visit;
     SpecimenTypeDirectory specimenTypeDirectory;
     studies study;
     String sponsorShip;
     SpecimenTypes specimenTypes;
     Patients patient;
//    public LabtechnicianAddspecimen() {
//        initComponents();
//    }

//    LabtechnicianAddspecimen(JPanel userProcessContainer, Visits visit) {
////        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//           initComponents();
//           this.userProcessContainer = userProcessContainer;
//           this.visit = visit;
//
//    
//    }

    LabtechnicianAddspecimen(JPanel userProcessContainer, Visits visit, SpecimenTypeDirectory specimenTypeDirectory, studies study, Patients patient) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   
             initComponents();
           this.userProcessContainer = userProcessContainer;
           this.visit = visit;
           this.specimenTypeDirectory = specimenTypeDirectory;
           this.study=study;
            sponsorShip = study.getSponsorship();
            this.patient = patient;
        
       
           
           jComboBox1.removeAllItems();
       for(SpecimenTypes s : this.specimenTypeDirectory.getSpecimenTypeDirectory()) {
//           System.out.println("Studies Loop ===>  "+s.getIrbID());
           jComboBox1.addItem(s);
       }
        
       if(jComboBox1.getSelectedItem()!=null)    
       calculateRate();
       
       
    
    }
    
    public void calculateRate(){
        
          specimenTypes = (SpecimenTypes)jComboBox1.getSelectedItem();
        if(sponsorShip == "Industry"){
            rateTF.setText(specimenTypes.getSponsoredrate());
        }else {
             rateTF.setText(specimenTypes.getSponsoredrate());
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        quantityTF = new javax.swing.JTextField();
        collectorTF = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        unitTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        slTF = new javax.swing.JTextField();
        csTF = new javax.swing.JTextField();
        ccTF = new javax.swing.JTextField();
        asTF = new javax.swing.JTextField();
        rateTF = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sbTF = new javax.swing.JTextField();
        collectionDateChooser = new com.toedter.calendar.JDateChooser();
        receivedDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        storageTF1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B & W Oncology Lab Technician ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Specimen Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Quantity:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Unit:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Collection Date:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Collector:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Receiver:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 160, -1));

        quantityTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(quantityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 150, -1));

        collectorTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(collectorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 150, -1));

        jTextField4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 150, -1));

        unitTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        unitTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitTFActionPerformed(evt);
            }
        });
        add(unitTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 150, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Received Date:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel9.setText("Activity Status:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel10.setText("Collection Container:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel12.setText("Rate:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel13.setText("Collection Status:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        slTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        slTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slTFActionPerformed(evt);
            }
        });
        add(slTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 160, -1));

        csTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(csTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 176, -1));

        ccTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(ccTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 176, -1));

        asTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(asTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 176, -1));

        rateTF.setEditable(false);
        rateTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(rateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 176, -1));

        submitbtn.setBackground(new java.awt.Color(18, 51, 105));
        submitbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 140, 50));

        backbtn.setBackground(new java.awt.Color(18, 51, 105));
        backbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<< Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 160, 50));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel11.setText("Specimen Label");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("Specimen Barcode");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        sbTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(sbTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 170, -1));
        add(collectionDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 150, 40));
        add(receivedDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 170, 40));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel15.setText("Storage Location:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        storageTF1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        storageTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageTF1ActionPerformed(evt);
            }
        });
        add(storageTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 176, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel16.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel16.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void slTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_slTFActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         if(jComboBox1.getSelectedItem()!=null)    
        calculateRate();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        
          userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabtechnicianCollectspecimen labtechnicianCollectspecimen = (LabtechnicianCollectspecimen) component;
        labtechnicianCollectspecimen.refreshVisitsTable(study, patient);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_backbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        try {
        if(slTF.getText().isEmpty() || sbTF.getText().isEmpty() || quantityTF.getText().isEmpty() 
                || ccTF.getText().isEmpty() || unitTF.getText().isEmpty() || csTF.getText().isEmpty() || asTF.getText().isEmpty() 
                || collectorTF.getText().isEmpty() || rateTF.getText().isEmpty() || jTextField4.getText().isEmpty() || collectionDateChooser.getDate() == null || receivedDateChooser1.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "Please enter missing fields");
        }
        else{
        Specimen  specimen= this.visit.getSpecimenDirectory().addspecimen();
        specimen.setSpecimenLabel(slTF.getText());
        specimen.setSpecimenBarcode(sbTF.getText());
        
        specimen.setSpecimen_type(jComboBox1.getSelectedItem().toString());
        specimen.setCollection_container(ccTF.getText());
        specimen.setCollection_date(collectionDateChooser.getDate());
        specimen.setCollection_status(csTF.getText());
        specimen.setCollector(collectorTF.getText());
        specimen.setQuantity((Integer.parseInt(quantityTF.getText())));
        specimen.setRate(rateTF.getText());
        specimen.setReceived_date(receivedDateChooser1.getDate());
        specimen.setReceiver(jTextField4.getText());
        specimen.setUnit(Integer.parseInt(unitTF.getText()));
        specimen.setStorage_location(storageTF1.getText());
JOptionPane.showMessageDialog(null, "Data saved successfully");
slTF.setText("");
sbTF.setText("");
quantityTF.setText("");
ccTF.setText("");
unitTF.setText("");
csTF.setText("");
asTF.setText("");
csTF.setText("");
collectorTF.setText("");
rateTF.setText("");
jTextField4.setText("");
        }
        }    
        catch( Exception e){
            JOptionPane.showMessageDialog(null, "Enter interger values for Quantity and Unit");
        }
        
    }//GEN-LAST:event_submitbtnActionPerformed

    private void storageTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storageTF1ActionPerformed

    private void unitTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asTF;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField ccTF;
    private com.toedter.calendar.JDateChooser collectionDateChooser;
    private javax.swing.JTextField collectorTF;
    private javax.swing.JTextField csTF;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JTextField rateTF;
    private com.toedter.calendar.JDateChooser receivedDateChooser1;
    private javax.swing.JTextField sbTF;
    private javax.swing.JTextField slTF;
    private javax.swing.JTextField storageTF1;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField unitTF;
    // End of variables declaration//GEN-END:variables
}
