/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabTechnicianRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Stakeholders.PatientsDirectory;
import Business.Stakeholders.SpecimenTypeDirectory;
import Business.Stakeholders.studiesDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.AdministrativeRole.ManageOrganizationJPanel;
import userinterface.CRCAdminRole.CRCAdminManageStudyPanel;

/**
 *
 * @author shubh
 */
public class LabtechnicianWorkarea extends javax.swing.JPanel {
    
    
    JPanel userProcessContainer;
    UserAccount account;
    LabOrganization labOrganization;
    EcoSystem business;
    
    PatientsDirectory patientsDirectory;
    SpecimenTypeDirectory specimenTypeDirectory;
    studiesDirectory studiesdirectory;
    Enterprise enterprise;

    /**
     * Creates new form labtechnician_workarea
     */
    public LabtechnicianWorkarea() {
        initComponents();
    }

    public LabtechnicianWorkarea(JPanel userProcessContainer,Enterprise enterprise, UserAccount account, LabOrganization labOrganization, EcoSystem business, PatientsDirectory patientsDirectory, SpecimenTypeDirectory specimenTypeDirectory, studiesDirectory studiesdirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     initComponents();
     this.enterprise=enterprise;
     this.userProcessContainer = userProcessContainer;
     this.account=account;
      this.labOrganization = labOrganization;
      this.business=business;
     this.patientsDirectory = patientsDirectory;
     this.studiesdirectory = studiesdirectory;
     this.specimenTypeDirectory = specimenTypeDirectory;
     jLabel1.setText(labOrganization.getName());
     
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        csbtn = new javax.swing.JButton();
        ssbtn = new javax.swing.JButton();
        KitRequestbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("l");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 16, 140, 20));

        csbtn.setBackground(new java.awt.Color(18, 51, 105));
        csbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        csbtn.setForeground(new java.awt.Color(255, 255, 255));
        csbtn.setText("Manage Specimen");
        csbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csbtnActionPerformed(evt);
            }
        });
        add(csbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 270, 50));

        ssbtn.setBackground(new java.awt.Color(18, 51, 105));
        ssbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        ssbtn.setForeground(new java.awt.Color(255, 255, 255));
        ssbtn.setText("Ship Specimen");
        ssbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssbtnActionPerformed(evt);
            }
        });
        add(ssbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 270, 50));

        KitRequestbtn.setBackground(new java.awt.Color(18, 51, 105));
        KitRequestbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        KitRequestbtn.setForeground(new java.awt.Color(255, 255, 255));
        KitRequestbtn.setText("Manage Kit Request");
        KitRequestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KitRequestbtnActionPerformed(evt);
            }
        });
        add(KitRequestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 270, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void csbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csbtnActionPerformed
        // TODO add your handling code here:
//            LabtechnicianCollectspecimen labtechnicianCollectspecimen = new LabtechnicianCollectspecimen(userProcessContainer, enterprise.getOrganizationDirectory());
           LabtechnicianCollectspecimen labtechnicianCollectspecimen = new LabtechnicianCollectspecimen(userProcessContainer, labOrganization, studiesdirectory, patientsDirectory, specimenTypeDirectory);
        userProcessContainer.add("LabtechnicianCollectspecimen", labtechnicianCollectspecimen);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
            
            
//            
//            userProcessContainer.add("LabtechnicianCollectspecimen", labtechnicianCollectspecimen);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        
        
        
    }//GEN-LAST:event_csbtnActionPerformed

    private void ssbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssbtnActionPerformed
        // TODO add your handling code here:
         ShipSpecimenJPanel shipSpecimenJPanel = new ShipSpecimenJPanel(userProcessContainer,account, labOrganization, studiesdirectory, patientsDirectory, specimenTypeDirectory,business);
        userProcessContainer.add("ShipSpecimenJPanel", shipSpecimenJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ssbtnActionPerformed

    private void KitRequestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KitRequestbtnActionPerformed
        // TODO add your handling code here:
             ManageKitRequestJPanel manageKitRequestJPanel = new ManageKitRequestJPanel(userProcessContainer, account, enterprise,business);
//           LabtechnicianCollectspecimen labtechnicianCollectspecimen = new LabtechnicianCollectspecimen(userProcessContainer, labOrganization, studiesdirectory, patientsDirectory, specimenTypeDirectory);
      
//                userProcessContainer.add("ManageKitRequestJPanel", new RequestLabTestJPanel(userProcessContainer, userAccount, enterprise));

        userProcessContainer.add("ManageKitRequestJPanel", manageKitRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_KitRequestbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KitRequestbtn;
    private javax.swing.JButton csbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton ssbtn;
    // End of variables declaration//GEN-END:variables
}
