/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SuperAdmin;

/**
 *
 * @author harish
 */
public class SuperAdminAddSitePanel extends javax.swing.JPanel {

    /**
     * Creates new form SuperAdminAddSitePanel
     */
    public SuperAdminAddSitePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSiteName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSiteAddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtCreatedDate = new com.toedter.calendar.JDateChooser();
        Submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("B&W Super Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 26));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Site Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, 30));

        txtSiteName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtSiteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 189, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Site Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, 29));

        txtSiteAddress.setColumns(20);
        txtSiteAddress.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        txtSiteAddress.setRows(5);
        jScrollPane1.setViewportView(txtSiteAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 189, 55));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Created Date:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 160, 28));
        add(txtCreatedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 189, -1));

        Submit.setBackground(new java.awt.Color(18, 51, 105));
        Submit.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 130, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel5.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel5.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser txtCreatedDate;
    private javax.swing.JTextArea txtSiteAddress;
    private javax.swing.JTextField txtSiteName;
    // End of variables declaration//GEN-END:variables
}
