/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SuperAdmin;

import Business.Enterprise.Enterprise;
import Business.Stakeholders.Patients;
import Business.Stakeholders.SpecimenTypeDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Stakeholders.SpecimenTypes;


/**
 *
 * @author harish
 */
public class SuperAdminManageSpecimenPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuperAdminManageSpecimenPanel
     */
//    public SuperAdminManageSpecimenPanel() {
//        initComponents();
//    }
    
       private JPanel userProcessContainer;
        private Enterprise enterprise;
         private  SpecimenTypeDirectory specimenTypeDirectory;


    public SuperAdminManageSpecimenPanel(JPanel container, Enterprise enterprise, SpecimenTypeDirectory specimenTypeDirectory) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = container;
        txtOrganizationName.setText(enterprise.getName());
        this.specimenTypeDirectory = specimenTypeDirectory;
        jLabel1.setText(enterprise.getName());
        refreshTable();
//        popOrganizationComboBox();
//       // employeeJComboBox.removeAllItems();
//        popData();
    }
    
     public void refreshTable() {
        int rowCount = tblManageSite.getRowCount();
        DefaultTableModel model = (DefaultTableModel)tblManageSite.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        if(specimenTypeDirectory !=null){
        
        for(SpecimenTypes a : specimenTypeDirectory.getSpecimenTypeDirectory()) {
            Object row[] = new Object[2];
            row[0] = a;
            row[1] = a.getCreateeddate();
//            row[2] = a.getCreateeddate();
//            row[3]
            model.addRow(row);
            }
        }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOrganizationName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageSite = new javax.swing.JTable();
        btnAddSpecimen = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Al Bayan", 0, 24)); // NOI18N
        jLabel1.setText("B&W Super Admin ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 580, 26));

        jLabel2.setFont(new java.awt.Font("Al Bayan", 0, 24)); // NOI18N
        jLabel2.setText("Organization Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 240, -1));

        txtOrganizationName.setFont(new java.awt.Font("Al Bayan", 0, 24)); // NOI18N
        txtOrganizationName.setEnabled(false);
        txtOrganizationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrganizationNameActionPerformed(evt);
            }
        });
        add(txtOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 158, 37));

        tblManageSite.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        tblManageSite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Specimen Type", "Created Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageSite);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 211));

        btnAddSpecimen.setBackground(new java.awt.Color(18, 51, 105));
        btnAddSpecimen.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnAddSpecimen.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSpecimen.setText("Add Specimen");
        btnAddSpecimen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSpecimenActionPerformed(evt);
            }
        });
        add(btnAddSpecimen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 190, 50));

        backJButton.setBackground(new java.awt.Color(18, 51, 105));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 130, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSpecimenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSpecimenActionPerformed
        // TODO add your handling code here:
         
           SuperAdminAddSpecimanJPanel muajp = new SuperAdminAddSpecimanJPanel(userProcessContainer, enterprise,specimenTypeDirectory);
        userProcessContainer.add("SuperAdminAddSpecimanJPanel", muajp);
//          SuperAdminManageSpecimenPanel muajp = new SuperAdminManageSpecimenPanel(userProcessContainer, enterprise);
//        userProcessContainer.add("SuperAdminAddspecimenPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAddSpecimenActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtOrganizationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrganizationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrganizationNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddSpecimen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageSite;
    private javax.swing.JTextField txtOrganizationName;
    // End of variables declaration//GEN-END:variables
}
