/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SuperAdmin;

import java.awt.CardLayout;

/**
 *
 * @author harish
 */
public class SuperAdminManageSitePanel extends javax.swing.JPanel {

    /**
     * Creates new form SuperAdminManageSitePanel
     */
    public SuperAdminManageSitePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtOrganizationName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageSite = new javax.swing.JTable();
        btnAddSite = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("B&W Super Admin Site");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 250, 26));

        txtOrganizationName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        txtOrganizationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrganizationNameActionPerformed(evt);
            }
        });
        add(txtOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 158, 37));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Organization Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, -1));

        tblManageSite.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        tblManageSite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Site Name", "Site Address", "Created On"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageSite);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 211));

        btnAddSite.setBackground(new java.awt.Color(18, 51, 105));
        btnAddSite.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnAddSite.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSite.setText("Add Site");
        btnAddSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSiteActionPerformed(evt);
            }
        });
        add(btnAddSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 430, 150, 50));

        backJButton.setBackground(new java.awt.Color(18, 51, 105));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 120, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 2000, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSiteActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        
//        userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtOrganizationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrganizationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrganizationNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddSite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageSite;
    private javax.swing.JTextField txtOrganizationName;
    // End of variables declaration//GEN-END:variables
}
