/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SuperAdmin;

import Business.Enterprise.Enterprise;
import Business.Stakeholders.Patients;
import Business.Stakeholders.SpecimenTypeDirectory;
import Business.Stakeholders.SpecimenTypes;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harish
 */

public class SuperAdminAddSpecimanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuperAdminAddSpecimanJPanel
     */
               private  SpecimenTypeDirectory specimenTypeDirectory;
               private SpecimenTypes specimenTypes;

    private JPanel userProcessContainer;
    private Enterprise enterprise;

    public SuperAdminAddSpecimanJPanel(JPanel container, Enterprise enterprise,SpecimenTypeDirectory specimenTypeDirectory) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = container;
        this.specimenTypeDirectory = specimenTypeDirectory;
        jLabel1.setText(enterprise.getName());

//        popOrganizationComboBox();
//       // employeeJComboBox.removeAllItems();
//        popData();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        rateTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rateTF1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Specimen Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 30));

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "protein", "RNA nuclear", "RNA", "poly-A enriched", "Slide" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 228, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel12.setText("Sponsored Rate:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        rateTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(rateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 176, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Created Date:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel13.setText("UnSponsored Rate:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        rateTF1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        rateTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTF1ActionPerformed(evt);
            }
        });
        add(rateTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 176, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B & W Oncology Lab Technician");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        submitbtn.setBackground(new java.awt.Color(18, 51, 105));
        submitbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 130, 50));

        backbtn.setBackground(new java.awt.Color(18, 51, 105));
        backbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<< Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
//        userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
          userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SuperAdminManageSpecimenPanel superAdminManageSpecimenPanel = (SuperAdminManageSpecimenPanel) component;
        superAdminManageSpecimenPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
         
    }//GEN-LAST:event_backbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        
                
     try{
        
        if(rateTF.getText().isEmpty() || rateTF1.getText().isEmpty() || jDateChooser1.getDate()==null){
          
          JLabel label = new JLabel("Sponsored and Unsposored rates Cannot be Empty!");
        label.setFont(new Font("Arial", Font.PLAIN, 18));
        JOptionPane.showMessageDialog(null,label,"Message",JOptionPane.INFORMATION_MESSAGE);

      }else{
          
          
          SpecimenTypes specimentype = specimenTypeDirectory.addSpecimenType();
          specimentype.setSpeciMenType((String)jComboBox1.getSelectedItem());
          specimentype.setCreateeddate(jDateChooser1.getDate());
          specimentype.setSponsoredrate(rateTF.getText());
          specimentype.setUnSposoredRate(rateTF1.getText());

          
//          
//         Date datedob = dobDateChooser.getDate();
//         
////        String strDate = DateFormat.getDateInstance().format(date);
//        patients.setPatientDOB(datedob);
//        
//        Date createdDate = createdDateChooser.getDate();
//        patients.setpCreatedDate(createdDate);
//        
//         String vitalStatus = (String)viewStatusCombo.getSelectedItem();
//         patients.setViewStatus(vitalStatus);
//         
//         String ActivityStatus = (String)activityStatusCombo.getSelectedItem();
//         patients.setActivityStatus(ActivityStatus);
//          
         JLabel label = new JLabel("Specimen Successfully Added");
        label.setFont(new Font("Arial", Font.PLAIN, 18));
        JOptionPane.showMessageDialog(null,label,"Message",JOptionPane.INFORMATION_MESSAGE);
        rateTF.setText("");
        rateTF1.setText("");
          
      }
        
     }catch(Exception e){
       //JOptionPane.showMessageDialog(null, "Please enter All Details"); 
         System.out.println(""+e);
         
//         JLabel label = new JLabel("Please Enter valid  Details!");
//        label.setFont(new Font("Arial", Font.PLAIN, 18));
//        JOptionPane.showMessageDialog(null,label,"Message",JOptionPane.INFORMATION_MESSAGE);

     }
        
        
        
        
        
    }//GEN-LAST:event_submitbtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void rateTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateTF1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField rateTF;
    private javax.swing.JTextField rateTF1;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
