/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

/**
 *
 * @author Gaurav
 */
public class CRCAdminViewVisitPanel extends javax.swing.JPanel {

    /**
     * Creates new form SiteAdminViewVisitPanel
     */
    public CRCAdminViewVisitPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVisitLabel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        visitsiteComboBox = new javax.swing.JComboBox();
        Day = new javax.swing.JLabel();
        visitDayComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("B&W Site Admin - Work Area > Manage Visit > View Visit");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 630, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Visit Label");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 120, 30));

        txtVisitLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(txtVisitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Visit Site");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 100, 30));

        visitsiteComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        visitsiteComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(visitsiteComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 170, 30));

        Day.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Day.setText("Day");
        add(Day, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 50, 30));

        visitDayComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        visitDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(visitDayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 170, 30));

        jButton1.setBackground(new java.awt.Color(18, 51, 105));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 101, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel4.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel4.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Day;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtVisitLabel;
    private javax.swing.JComboBox visitDayComboBox;
    private javax.swing.JComboBox visitsiteComboBox;
    // End of variables declaration//GEN-END:variables
}
