/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

import Business.Organization.OncologyDepartment;
import Business.Stakeholders.Patients;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Stakeholders.studiesDirectory;
import Business.Stakeholders.studies;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shubh
 */
public class CRCAdminManageStudyPanel extends javax.swing.JPanel {

    /**
     * Creates new form siteadmin_workarea_managestudy
     */
//    public CRCAdminManageStudyPanel() {
//        initComponents();
//    }
    JPanel userProcessContainer;
    private OncologyDepartment organization;
    private studiesDirectory stDirectory;
    

    CRCAdminManageStudyPanel(JPanel userProcessContainer, OncologyDepartment organization, studiesDirectory stDirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   initComponents();
   this.userProcessContainer = userProcessContainer;
   this.organization = organization;
   sitenameTF.setText(organization.getName());
   this.stDirectory =  stDirectory;
   jLabel1.setText(organization.getName());
   
   refreshTable();
    }
    
    
    public void refreshTable() {
        int rowCount = managestudytbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel)managestudytbl.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(studies a : stDirectory.getStudyList()) {
            Object row[] = new Object[3];
            row[0] = a;
            row[1] = a.getIrbID();
            row[2] = a.getStartDate();
//            row[3]
            model.addRow(row);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sitenameTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        managestudytbl = new javax.swing.JTable();
        addstudybtn = new javax.swing.JButton();
        addconsentbtn = new javax.swing.JButton();
        viewconsentbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B & W Oncology Site Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Site Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        sitenameTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        sitenameTF.setEnabled(false);
        add(sitenameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 200, -1));

        managestudytbl.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        managestudytbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Study Title", "IRB id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(managestudytbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 238));

        addstudybtn.setBackground(new java.awt.Color(18, 51, 105));
        addstudybtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addstudybtn.setForeground(new java.awt.Color(255, 255, 255));
        addstudybtn.setText("Add Study");
        addstudybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudybtnActionPerformed(evt);
            }
        });
        add(addstudybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, 40));

        addconsentbtn.setBackground(new java.awt.Color(18, 51, 105));
        addconsentbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addconsentbtn.setForeground(new java.awt.Color(255, 255, 255));
        addconsentbtn.setText("Add Consent Questions");
        addconsentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addconsentbtnActionPerformed(evt);
            }
        });
        add(addconsentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 330, 50));

        viewconsentbtn.setBackground(new java.awt.Color(18, 51, 105));
        viewconsentbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        viewconsentbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewconsentbtn.setText("View Consent Questions");
        viewconsentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewconsentbtnActionPerformed(evt);
            }
        });
        add(viewconsentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 330, 50));

        backbtn.setBackground(new java.awt.Color(18, 51, 105));
        backbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<< Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addstudybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudybtnActionPerformed
        // TODO add your handling code here:
        
           CRCAdminAddStudyPanel manageOrganizationJPanel = new CRCAdminAddStudyPanel(userProcessContainer, organization, stDirectory);
        userProcessContainer.add("CRCAdminAddStudyPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_addstudybtnActionPerformed

    private void addconsentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addconsentbtnActionPerformed
        // TODO add your handling code here:
          

         int selectedRow = managestudytbl.getSelectedRow();
        if(selectedRow>=0){
            
                studies study = (studies)managestudytbl.getValueAt(selectedRow, 0);
                 CRCAdminAddConsentPanel manageOrganizationJPanel = new CRCAdminAddConsentPanel(userProcessContainer, organization, study);
        userProcessContainer.add("CRCAdminAddConsentPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);
            
        }else{
            //JOptionPane.showMessageDialog(null, "Please select a Row!!");
            JLabel label = new JLabel("Please select a Row!");
        label.setFont(new Font("Arial", Font.PLAIN, 18));
        JOptionPane.showMessageDialog(null,label,"Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
        
      

    }//GEN-LAST:event_addconsentbtnActionPerformed

    private void viewconsentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewconsentbtnActionPerformed
        // TODO add your handling code here:
        
        
                
                
                
         int selectedRow = managestudytbl.getSelectedRow();
        if(selectedRow>=0){
            
                studies study = (studies)managestudytbl.getValueAt(selectedRow, 0);
                 CRCAdminViewConsentPanel cRCAdminViewConsentPanel = new CRCAdminViewConsentPanel(userProcessContainer, organization, study);
        userProcessContainer.add("CRCAdminViewConsentPanel", cRCAdminViewConsentPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);
            
        }else{
            //JOptionPane.showMessageDialog(null, "Please select a Row!!");
            JLabel label = new JLabel("Please select a Row!");
        label.setFont(new Font("Arial", Font.PLAIN, 18));
        JOptionPane.showMessageDialog(null,label,"Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_viewconsentbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addconsentbtn;
    private javax.swing.JButton addstudybtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable managestudytbl;
    private javax.swing.JTextField sitenameTF;
    private javax.swing.JButton viewconsentbtn;
    // End of variables declaration//GEN-END:variables
}
