/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

import Business.Organization.OncologyDepartment;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import Business.Stakeholders.studies;
import Business.Stakeholders.studiesDirectory;
import Business.Stakeholders.ConsentQuestionsDirectory;
import Business.Stakeholders.ConsentQueations;
import javax.swing.JOptionPane;

/**
 *
 * @author shubh
 */
public class CRCAdminAddConsentPanel extends javax.swing.JPanel {

    /**
     * Creates new form siteadmin_workarea_managestudy_addconsent
     */
//    public CRCAdminAddConsentPanel() {
//        initComponents();
//    }
    JPanel userProcessContainer;
    OncologyDepartment organization;
    studies study;
//    ConsentQueations consentQueations;
    CRCAdminAddConsentPanel(JPanel userProcessContainer, OncologyDepartment organization,studies study) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.organization = organization;
            this.study = study;
            jLabel1.setText(organization.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cq2TF = new javax.swing.JTextField();
        cq1TF = new javax.swing.JTextField();
        cq4TF = new javax.swing.JTextField();
        cq3TF = new javax.swing.JTextField();
        cq5TF = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B & W  Site Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Question - 1:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Question - 2:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 174, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Question - 5:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 341, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Question - 4:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 286, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Question - 3:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 229, -1, -1));

        cq2TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(cq2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 491, -1));

        cq1TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        cq1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cq1TFActionPerformed(evt);
            }
        });
        add(cq1TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 491, -1));

        cq4TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(cq4TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 491, -1));

        cq3TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(cq3TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 491, -1));

        cq5TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(cq5TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 491, -1));

        submitbtn.setBackground(new java.awt.Color(18, 51, 105));
        submitbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 130, 50));

        jButton1.setBackground(new java.awt.Color(18, 51, 105));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 524, 130, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel4.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel4.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cq1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cq1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cq1TFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//         userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CRCAdminManageStudyPanel crcAdminManageStudyPanel = (CRCAdminManageStudyPanel) component;
        crcAdminManageStudyPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
if (cq1TF.getText().isEmpty() || cq2TF.getText().isEmpty()|| cq3TF.getText().isEmpty() || cq4TF.getText().isEmpty() || cq5TF.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter all questions or N/A in the fields");
        }
        else {
      study.setQuestion1(cq1TF.getText());
      study.setQuestion2(cq2TF.getText());
      study.setQuestion3(cq3TF.getText());
      study.setQuestion4(cq4TF.getText());
      study.setQuestion5(cq5TF.getText());
      
      JOptionPane.showMessageDialog(null, "Questions added successfully");
      
      cq1TF.setText("");
      cq2TF.setText("");
      cq3TF.setText("");
      cq4TF.setText("");
      cq5TF.setText("");
        } 
              
    }//GEN-LAST:event_submitbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cq1TF;
    private javax.swing.JTextField cq2TF;
    private javax.swing.JTextField cq3TF;
    private javax.swing.JTextField cq4TF;
    private javax.swing.JTextField cq5TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
