/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

import Business.Organization.OncologyDepartment;
import Business.Stakeholders.Patients;
import Business.Stakeholders.PatientsDirectory;
import Business.Stakeholders.Visits;
import Business.Stakeholders.VisitsDirectory;
import Business.Stakeholders.studies;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import Business.Stakeholders.Visits;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class CRCAdminAddVisitPanel extends javax.swing.JPanel {

    /**
     * Creates new form SiteAdminAddVisitPanel
     */
//    public CRCAdminAddVisitPanel() {
//        initComponents();
//    }
    JPanel userProcessContainer;
    OncologyDepartment organization;
      studies study;
    VisitsDirectory visitsDirectory;
      PatientsDirectory patientsDirectory;
    Visits visit;

    CRCAdminAddVisitPanel(JPanel userProcessContainer, OncologyDepartment organization,studies study,PatientsDirectory patientsDirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       initComponents();
      this.userProcessContainer = userProcessContainer;
      this.organization=organization;
      this.study= study;
      this.patientsDirectory = patientsDirectory;
      jLabel1.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVisitLabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        visitDayComboBox = new javax.swing.JComboBox();
        backBtn = new javax.swing.JButton();
        btnSubmit1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("B&W Site Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 350, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Visit Label");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 30));

        txtVisitLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        txtVisitLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVisitLabelActionPerformed(evt);
            }
        });
        add(txtVisitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Day");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 85, 30));

        visitDayComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        visitDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day 1", "Day 30", "Day 90", "Day 180" }));
        add(visitDayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 170, 30));

        backBtn.setBackground(new java.awt.Color(18, 51, 105));
        backBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 110, 50));

        btnSubmit1.setBackground(new java.awt.Color(18, 51, 105));
        btnSubmit1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnSubmit1.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit1.setText("Submit");
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });
        add(btnSubmit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtVisitLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVisitLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVisitLabelActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CRCAdminManageVisitPanel cRCAdminManageVisitPanel = (CRCAdminManageVisitPanel) component;
        cRCAdminManageVisitPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
        // TODO add your handling code here:
        if (txtVisitLabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter missing field");
        }
        else {
         visit = this.study.getVisitDirectory().addVisit();
        visit.setLabel(txtVisitLabel.getText());
//        visit.setSite((String)visitSitelComboBox.getSelectedItem());
        visit.setDay((String)visitDayComboBox.getSelectedItem());
        
        for(Patients p: patientsDirectory.getPatientDirectory()){
            if(this.study.getIrbID().equals(p.getStudyID())){
               Visits v= p.getVisitsDirectory().addVisit();
                v.setLabel(p.getMrn()+txtVisitLabel.getText());
//        v.setLabel(txtVisitLabel.getText());
//        v.setSite((String)visitSitelComboBox.getSelectedItem());
        v.setDay((String)visitDayComboBox.getSelectedItem());
        JOptionPane.showMessageDialog(null, "Data Added Successfully!");
               txtVisitLabel.setText("");
            }
        }}
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnSubmit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnSubmit1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtVisitLabel;
    private javax.swing.JComboBox visitDayComboBox;
    // End of variables declaration//GEN-END:variables
}
