/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

import Business.Organization.OncologyDepartment;
import Business.Stakeholders.Patients;
import Business.Stakeholders.PatientsDirectory;
import Business.Stakeholders.studies;
import Business.Stakeholders.studiesDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Stakeholders.VisitsDirectory;
import Business.Stakeholders.Visits;

/**
 *
 * @author shubh
 */
public class CRCAdminManageVisitPanel extends javax.swing.JPanel {

    /**
     * Creates new form siteadmin_workarea_managevisittemplate
     */
//    public CRCAdminManageVisitPanel() {
//        initComponents();
//    }
    JPanel userProcessContainer;
    OncologyDepartment organization;
   studiesDirectory stDirectory;
    PatientsDirectory patientsDirectory;
//    Visits visit;
    studies study;
    VisitsDirectory visitsDirectory;
     public  CRCAdminManageVisitPanel(JPanel userProcessContainer,  OncologyDepartment organization,studiesDirectory stDirectory,PatientsDirectory patientsDirectory ){
         
         initComponents();
         this.userProcessContainer = userProcessContainer;
         this.organization =organization;
         this.stDirectory=stDirectory;
         this.patientsDirectory=patientsDirectory;
         
          studyComboBox.removeAllItems();
       for(studies s : this.stDirectory.getStudyList()) {
           System.out.println("Studies Loop ===>  "+s.getIrbID());
           studyComboBox.addItem(s);
       }
   
        
    
   
     refreshTable(); 
     jLabel1.setText(organization.getName());
         
     }
     
      public void refreshTable() {
        int rowCount = visittbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel)visittbl.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
//        if(((((Airplane)jComboBox1.getSelectedItem())!=null) ) && (((Airplane)jComboBox1.getSelectedItem()).getFlightDirectory()!=null) && ((Airplane)jComboBox1.getSelectedItem()).getFlightDirectory().getFlightDirectory()!=null){
       if((studies)studyComboBox.getSelectedItem()!=null){
           
           studies study = (studies)studyComboBox.getSelectedItem();
           if(study.getVisitDirectory()!=null)
           for(Visits v : study.getVisitDirectory().getVisitList()) {
        
             Object row[] = new Object[2];
             row[0] = v;
             row[1] = v.getDay();
             
             model.addRow(row);
          
           
           
       }
        
          
        }
    }
     
     
     
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studyComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        visittbl = new javax.swing.JTable();
        addvisitbtn = new javax.swing.JButton();
        viewvisitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B & W Site Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Select Study:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        studyComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        studyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        studyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyComboBoxActionPerformed(evt);
            }
        });
        add(studyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        visittbl.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        visittbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Visit Lable", "Visit Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(visittbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 164, -1, 163));

        addvisitbtn.setBackground(new java.awt.Color(18, 51, 105));
        addvisitbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addvisitbtn.setForeground(new java.awt.Color(255, 255, 255));
        addvisitbtn.setText("Add  Visit");
        addvisitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvisitbtnActionPerformed(evt);
            }
        });
        add(addvisitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 160, 40));

        viewvisitbtn.setBackground(new java.awt.Color(18, 51, 105));
        viewvisitbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        viewvisitbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewvisitbtn.setText("View Visit");
        viewvisitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewvisitbtnActionPerformed(evt);
            }
        });
        add(viewvisitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 160, 40));

        backbtn.setBackground(new java.awt.Color(18, 51, 105));
        backbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<< Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 504, 140, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel3.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 2000, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addvisitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvisitbtnActionPerformed
        // TODO add your handling code here:
        
        studies study = (studies)studyComboBox.getSelectedItem();
           CRCAdminAddVisitPanel cRCAdminAddVisitPanel = new CRCAdminAddVisitPanel(userProcessContainer, organization,study, patientsDirectory);
        userProcessContainer.add("CRCAdminAddVisitPanel", cRCAdminAddVisitPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
        
    }//GEN-LAST:event_addvisitbtnActionPerformed

    private void studyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyComboBoxActionPerformed
        // TODO add your handling code here:
            refreshTable(); 
    }//GEN-LAST:event_studyComboBoxActionPerformed

    private void viewvisitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewvisitbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewvisitbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addvisitbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox studyComboBox;
    private javax.swing.JButton viewvisitbtn;
    private javax.swing.JTable visittbl;
    // End of variables declaration//GEN-END:variables
}
