/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

/**
 *
 * @author harish
 */
public class CRCAdminUpdateViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form CRCAdminUpdateViewPanel
     */
    public CRCAdminUpdateViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vcfq2TF = new javax.swing.JTextField();
        vcfq1TF = new javax.swing.JTextField();
        vcfq4TF = new javax.swing.JTextField();
        vcfq3TF = new javax.swing.JTextField();
        vcfq5TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        radioYes1 = new javax.swing.JRadioButton();
        radioNo1 = new javax.swing.JRadioButton();
        radioWithdrawn1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        savebtn = new javax.swing.JButton();
        bckbtn = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("B & W Site Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Question - 1:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Question - 2:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Question - 5:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Question - 4:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Question - 3:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 150, -1));

        vcfq2TF.setEditable(false);
        vcfq2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(vcfq2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 390, -1));

        vcfq1TF.setEditable(false);
        vcfq1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vcfq1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcfq1TFActionPerformed(evt);
            }
        });
        add(vcfq1TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 390, -1));

        vcfq4TF.setEditable(false);
        vcfq4TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(vcfq4TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 390, -1));

        vcfq3TF.setEditable(false);
        vcfq3TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(vcfq3TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 390, -1));

        vcfq5TF.setEditable(false);
        vcfq5TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(vcfq5TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 390, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("NO");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 109, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("YES");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 109, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("WITHDRAWN");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Consent Status:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Signed Date:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));
        add(radioYes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));
        add(radioNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));
        add(radioWithdrawn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, -1, -1));
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));
        add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));
        add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, -1));

        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));
        add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));
        add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));
        add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));
        add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));
        add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        savebtn.setBackground(new java.awt.Color(18, 51, 105));
        savebtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 90, 50));

        bckbtn.setBackground(new java.awt.Color(18, 51, 105));
        bckbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bckbtn.setForeground(new java.awt.Color(255, 255, 255));
        bckbtn.setText("<< Back");
        bckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckbtnActionPerformed(evt);
            }
        });
        add(bckbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 120, 50));

        jComboBox2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No", "Withdrawn" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 130, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel12.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel12.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void vcfq1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcfq1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcfq1TFActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:

        //        radioCustomer.setActionCommand("customer");
        //        radioSupplier.setActionCommand("supplier");

        radioYes1.setActionCommand("Yes");
        radioNo1.setActionCommand("No");
        radioWithdrawn1.setActionCommand("Withdrawn");

        //
        //        if(txtUser.getText().isEmpty()||txtPword.getText().isEmpty()||txtRePword.getText().isEmpty())
        //        {
            //            JOptionPane.showMessageDialog(null,"Please enter Valid data..");
            //        }

//        if(buttonGroup1.getSelection().getActionCommand() == "Yes"){
//            this.consentQueations.setRespose1("Yes");
//
//        }else if(buttonGroup1.getSelection().getActionCommand()== "No"){
//            this.consentQueations.setRespose1("No");
//
//        }else if(buttonGroup1.getSelection().getActionCommand()=="Withdrawn"){
//            this.consentQueations.setRespose1("Withdrawn");
//        }
//
//        if(buttonGroup2.getSelection().getActionCommand() == "Yes"){
//            this.consentQueations.setRespose2("Yes");
//
//        }else if(buttonGroup2.getSelection().getActionCommand()== "No"){
//            this.consentQueations.setRespose2("No");
//
//        }else if(buttonGroup2.getSelection().getActionCommand()=="Withdrawn"){
//            this.consentQueations.setRespose2("Withdrawn");
//        }
//
//        if(buttonGroup3.getSelection().getActionCommand() == "Yes"){
//            this.consentQueations.setResponse3("Yes");
//
//        }else if(buttonGroup3.getSelection().getActionCommand()== "No"){
//            this.consentQueations.setResponse3("No");
//
//        }else if(buttonGroup3.getSelection().getActionCommand()=="Withdrawn"){
//            this.consentQueations.setResponse3("Withdrawn");
//        }
//
//        if(buttonGroup4.getSelection().getActionCommand() == "Yes"){
//            this.consentQueations.setReponse4("Yes");
//
//        }else if(buttonGroup4.getSelection().getActionCommand()== "No"){
//            this.consentQueations.setReponse4("No");
//
//        }else if(buttonGroup4.getSelection().getActionCommand()=="Withdrawn"){
//            this.consentQueations.setReponse4("Withdrawn");
//        }
//
//        if(buttonGroup5.getSelection().getActionCommand() == "Yes"){
//            this.consentQueations.setReponse5("Yes");
//
//        }else if(buttonGroup5.getSelection().getActionCommand()== "No"){
//            this.consentQueations.setReponse5("No");
//
//        }else if(buttonGroup5.getSelection().getActionCommand()=="Withdrawn"){
//            this.consentQueations.setReponse5("Withdrawn");
//        }
//
//        this.consentQueations.setConsentStatus((String)jComboBox2.getSelectedItem());
//        this.consentQueations.setcCreatedDate(jDateChooser1.getDate());

        //
        //        if(groupBtn.getSelection().getActionCommand()== "customer" ){
            //            customer = customerDirectory.addCustomer();
            //            customer.setUserName(txtUser.getText());
            //            customer.setPassword(txtPword.getText());
            //
            //            JOptionPane.showMessageDialog(null,"Customer Successfully Created");
            //             txtUser.setText("");
            //            txtPword.setText("");
            //            txtRePword.setText("");
            //
            //        }
        //        else if(groupBtn.getSelection().getActionCommand()== "supplier"){
            //
            //            supplier = supplierDirectory.addSupplier();
            //            supplier.setUserName(txtUser.getText());
            //            supplier.setPassword(txtPword.getText());
            //
            //            JOptionPane.showMessageDialog(null,"Supplier Successfully Created");
            //            txtUser.setText("");
            //            txtPword.setText("");
            //            txtRePword.setText("");
            //        }
        //

    }//GEN-LAST:event_savebtnActionPerformed

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        // TODO add your handling code here:
//        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        CRCManageConsentPanel cecCManageConsentPanel = (CRCManageConsentPanel) component;
//        //        cecCManageConsentPanel.refreshTable();
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);

    }//GEN-LAST:event_bckbtnActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckbtn;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton radioNo1;
    private javax.swing.JRadioButton radioWithdrawn1;
    private javax.swing.JRadioButton radioYes1;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField vcfq1TF;
    private javax.swing.JTextField vcfq2TF;
    private javax.swing.JTextField vcfq3TF;
    private javax.swing.JTextField vcfq4TF;
    private javax.swing.JTextField vcfq5TF;
    // End of variables declaration//GEN-END:variables
}
