/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

import Business.Organization.OncologyDepartment;
import Business.Stakeholders.Patients;
import Business.Stakeholders.studies;
import Business.Stakeholders.studiesDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SuperAdmin.SuperAdminManagePatientPanel;

/**
 *
 * @author shubh
 */
public class CRCAdminAddStudyPanel extends javax.swing.JPanel {

    /**
     * Creates new form siteadmin_workarea_managestudy_addstudy
     */
//    public CRCAdminAddStudyPanel() {
//        initComponents();
//    }
    JPanel userProcessContainer;
    OncologyDepartment organization;
    private studiesDirectory stDirectory;


    CRCAdminAddStudyPanel(JPanel userProcessContainer, OncologyDepartment organization,studiesDirectory stDirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.organization = organization;
            this.stDirectory = stDirectory;
            jLabel1.setText(organization.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        studytitleTF = new javax.swing.JTextField();
        shorttitleTF = new javax.swing.JTextField();
        irbidTF = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        priInvTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B & W Oncology Site Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Study Title:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Short Title:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Start Date:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("IRB id:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Closed", "Disables" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 140, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Activity Status:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Principle Investgator:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Sponsorship:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sponsered", "UnSponsered" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));

        studytitleTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        studytitleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studytitleTFActionPerformed(evt);
            }
        });
        add(studytitleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 135, -1));

        shorttitleTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(shorttitleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 135, -1));

        irbidTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(irbidTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 140, -1));

        submitbtn.setBackground(new java.awt.Color(18, 51, 105));
        submitbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, -1, -1));

        backbtn.setBackground(new java.awt.Color(18, 51, 105));
        backbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<< Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 140, 40));

        priInvTF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(priInvTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 140, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel9.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel9.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void studytitleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studytitleTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studytitleTFActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CRCAdminManageStudyPanel cRCAdminManageStudyPanel = (CRCAdminManageStudyPanel) component;
        cRCAdminManageStudyPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
//         userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
           try{
        
        if(studytitleTF.getText().isEmpty() || shorttitleTF.getText().isEmpty() || irbidTF.getText().isEmpty() || priInvTF.getText().isEmpty()){
          
          JLabel label = new JLabel("Study Title   and Short Title  Cannot be Empty!");
        label.setFont(new Font("Arial", Font.PLAIN, 18));
        JOptionPane.showMessageDialog(null,label,"Message",JOptionPane.INFORMATION_MESSAGE);

      }else{
          
          
          studies study = stDirectory.addStudy();
          
          
          study.setStudyTitle(studytitleTF.getText());
          study.setShortTitle(shorttitleTF.getText());
          study.setStartDate(jDateChooser1.getDate());
          study.setIrbID(irbidTF.getText());
          study.setPrincipleInvestigator(priInvTF.getText());
          
//          patients.setMrn(txtMRN.getText());
          
          
//         Date datedob = dobDateChooser.getDate();
         
//        String strDate = DateFormat.getDateInstance().format(date);
//        patients.setPatientDOB(datedob);
//        
//        Date createdDate = createdDateChooser.getDate();
//        patients.setpCreatedDate(createdDate);
//        
//         String vitalStatus = (String)viewStatusCombo.getSelectedItem();
//         patients.setViewStatus(vitalStatus);
         
         String ActivityStatus = (String)jComboBox1.getSelectedItem();
         study.setActivityStatus(ActivityStatus);
         
          String sponsoredStatus = (String)jComboBox3.getSelectedItem();
         study.setSponsorship(sponsoredStatus);
         
          
         JLabel label = new JLabel("Study Successfully Added");
        label.setFont(new Font("Arial", Font.PLAIN, 18));
        JOptionPane.showMessageDialog(null,label,"Message",JOptionPane.INFORMATION_MESSAGE);
        studytitleTF.setText("");
        shorttitleTF.setText("");
        irbidTF.setText("");
        priInvTF.setText("");
          
      }
        
     }catch(Exception e){
       //JOptionPane.showMessageDialog(null, "Please enter All Details"); 
         System.out.println(""+e);
         
//         JLabel label = new JLabel("Please Enter valid  Details!");
//        label.setFont(new Font("Arial", Font.PLAIN, 18));
//        JOptionPane.showMessageDialog(null,label,"Message",JOptionPane.INFORMATION_MESSAGE);

     }
        
        
        
        
        
    }//GEN-LAST:event_submitbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField irbidTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField priInvTF;
    private javax.swing.JTextField shorttitleTF;
    private javax.swing.JTextField studytitleTF;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
