/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

import Business.Enterprise.ClinicalLabEnterprise;
import Business.Enterprise.Enterprise;
//import Business.Organization.DoctorOrganization;
import Business.Organization.OncologyDepartment;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.AdministrativeRole.ManageOrganizationJPanel;
import Business.Stakeholders.studiesDirectory;
import Business.Stakeholders.studies;
import Business.Stakeholders.PatientsDirectory;
import Business.Stakeholders.SpecimenTypeDirectory;
import Business.Enterprise.ClinicalLabEnterprise;




/**
 *
 * @author shubh
 */
public class CRCadminWorkareaPanel extends javax.swing.JPanel {

    /**
     * Creates new form siteadmin_workarea
     */
//    public CRCadminWorkareaPanel() {
//        initComponents();
//    }
//
//    public CRCadminWorkareaPanel(JPanel userProcessContainer, Enterprise enterprise) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
// JPanel userProcessContainer;
//    Enterprise enterprise;
    /**
     * Creates new form SuperAdminWorkArea
     */
//    public SuperAdminWorkAreaPanel() {
//        initComponents();
//    }
//     public CRCadminWorkareaPanel(JPanel userProcessContainer, Enterprise enterprise) {
//        initComponents();
//        this.userProcessContainer = userProcessContainer;
//        this.enterprise = enterprise;
////        enterpriseNameLabel.setText(enterprise.getName());
//    
    private JPanel userProcessContainer;
    private OncologyDepartment organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private studiesDirectory studiesdirectory;
    private PatientsDirectory patientsDirectory;
    private  SpecimenTypeDirectory specimenTypeDirectory;
        private ClinicalLabEnterprise clinicalLabEnterprise;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CRCadminWorkareaPanel(JPanel userProcessContainer, UserAccount account, OncologyDepartment organization, Enterprise enterprise,studiesDirectory studiesdirectory,PatientsDirectory patientsDirectory,SpecimenTypeDirectory specimenTypeDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.studiesdirectory = studiesdirectory;
        this.patientsDirectory = patientsDirectory;
        this.specimenTypeDirectory = specimenTypeDirectory;
        
          
        clinicalLabEnterprise =(ClinicalLabEnterprise)enterprise;
        jLabel1.setText(organization.getName());
//       if(patientsDirectory == null)  
//        patientsDirectory = clinicalLabEnterprise.getPatientsDirectory();//new PatientsDirectory();
//        
////       if(specimenTypeDirectory==null) 
//       specimenTypeDirectory = clinicalLabEnterprise.getSpecimenTypeDirectory();
//        this.patientsDirectory = patientsDirectory;
       
//        if(studiesdirectory == null)
//        studiesdirectory = new studiesDirectory();
//        initComponents();
//        valueLabel.setText(enterprise.getName());
//        populateRequestTable();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        managestudybtn = new javax.swing.JButton();
        managepatientbtn = new javax.swing.JButton();
        consentformbtn = new javax.swing.JButton();
        visitsbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("l");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 318, 52));

        managestudybtn.setBackground(new java.awt.Color(18, 51, 105));
        managestudybtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        managestudybtn.setForeground(new java.awt.Color(255, 255, 255));
        managestudybtn.setText("Manage Study");
        managestudybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managestudybtnActionPerformed(evt);
            }
        });
        add(managestudybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 330, 50));

        managepatientbtn.setBackground(new java.awt.Color(18, 51, 105));
        managepatientbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        managepatientbtn.setForeground(new java.awt.Color(255, 255, 255));
        managepatientbtn.setText("Manage Patient");
        managepatientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managepatientbtnActionPerformed(evt);
            }
        });
        add(managepatientbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 330, 50));

        consentformbtn.setBackground(new java.awt.Color(18, 51, 105));
        consentformbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        consentformbtn.setForeground(new java.awt.Color(255, 255, 255));
        consentformbtn.setText("Manage Consent Form");
        consentformbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consentformbtnActionPerformed(evt);
            }
        });
        add(consentformbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 330, 50));

        visitsbtn.setBackground(new java.awt.Color(18, 51, 105));
        visitsbtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        visitsbtn.setForeground(new java.awt.Color(255, 255, 255));
        visitsbtn.setText("Manage Visits");
        visitsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitsbtnActionPerformed(evt);
            }
        });
        add(visitsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 330, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel2.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel2.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void managestudybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managestudybtnActionPerformed
        // TODO add your handling code here:
           CRCAdminManageStudyPanel manageOrganizationJPanel = new CRCAdminManageStudyPanel(userProcessContainer, organization, studiesdirectory);
        userProcessContainer.add("CRCAdminManageStudyPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managestudybtnActionPerformed

    private void managepatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managepatientbtnActionPerformed
        // TODO add your handling code here:
               CRCAdminManagePatientPanel cRCAdminManagePatientPanel = new CRCAdminManagePatientPanel(userProcessContainer, organization,studiesdirectory,patientsDirectory);
        userProcessContainer.add("CRCAdminManagePatientPanel", cRCAdminManagePatientPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managepatientbtnActionPerformed

    private void consentformbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consentformbtnActionPerformed
        // TODO add your handling code here:
        
         CRCManageConsentPanel cRCManageConsentPanel = new CRCManageConsentPanel(userProcessContainer, organization,studiesdirectory,patientsDirectory );
        userProcessContainer.add("CRCManageConsentPanel", cRCManageConsentPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_consentformbtnActionPerformed

    private void visitsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitsbtnActionPerformed
        // TODO add your handling code here:
          CRCAdminManageVisitPanel cRCAdminManageVisitPanel = new CRCAdminManageVisitPanel(userProcessContainer, organization,studiesdirectory,patientsDirectory );
        userProcessContainer.add("CRCAdminManageVisitPanel", cRCAdminManageVisitPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_visitsbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consentformbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton managepatientbtn;
    private javax.swing.JButton managestudybtn;
    private javax.swing.JButton visitsbtn;
    // End of variables declaration//GEN-END:variables
}
