/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

import Business.Organization.OncologyDepartment;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Stakeholders.studiesDirectory;
import Business.Stakeholders.studies;
import Business.Stakeholders.Patients;
import Business.Stakeholders.PatientsDirectory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shubh
 */
public class CRCAdminManagePatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form siteadmin_workarea_managepatient
     */
//    public CRCAdminManagePatientPanel() {
//        initComponents();
//    }
    JPanel userProcessContainer;
    OncologyDepartment organization; 
    studiesDirectory stDirectory;
    PatientsDirectory patientsDirectory;
    CRCAdminManagePatientPanel(JPanel userProcessContainer, OncologyDepartment organization, studiesDirectory stDirectory,PatientsDirectory patientsDirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   initComponents();;
   this.userProcessContainer = userProcessContainer;
   this.organization = organization;
   this.stDirectory = stDirectory;
   this.patientsDirectory=patientsDirectory;
   jLabel1.setText(organization.getName());
   
    
     studyComboBox.removeAllItems();
       for(studies s : this.stDirectory.getStudyList()) {
           System.out.println("Studies Loop ===>  "+s.getIrbID());
           studyComboBox.addItem(s);
       }
   
        
     patientComboBox.removeAllItems();
       for(Patients p : this.patientsDirectory.getPatientDirectory()) {
         System.out.println("Patients Loop ===>  "+p.getStudyID());

           patientComboBox.addItem(p);
       }
   
     refreshTable();  
    }
    
    public void refreshTable() {
                     System.out.println("1111111 Inside RefreshTable - ");

        int rowCount = mptbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel)mptbl.getModel();
        
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }

        
        for(studies s : this.stDirectory.getStudyList()) {
            System.out.println("22222222 Inside RefreshTable - outsideloop");
            
            for(Patients patients : this.patientsDirectory.getPatientDirectory()){
             System.out.println("3333333 Inside RefreshTable - insideloop");

                
                if(s.getIrbID().equals(patients.getStudyID()) ){
          System.out.println("444444444 Inside RefreshTable - Inside condition $$$$$");
                   Object row[] = new Object[3];

            row[0] = s;
            row[1] = s.getIrbID();
            row[2] = patients.getPatientName();
            model.addRow(row);
                }
                
            }
           
                
              
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studyComboBox = new javax.swing.JComboBox();
        patientComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mptbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B & W Oncology Site Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Select Study:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Select Patient:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 20));

        studyComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        studyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(studyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        patientComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        patientComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(patientComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        jButton1.setBackground(new java.awt.Color(18, 51, 105));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        mptbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Study Name", "Study ID", "Patient Name"
            }
        ));
        jScrollPane1.setViewportView(mptbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 510, 230));

        jButton2.setBackground(new java.awt.Color(18, 51, 105));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel4.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel4.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       studies study = (studies)studyComboBox.getSelectedItem();
       Patients patients = (Patients)patientComboBox.getSelectedItem();
       patients.setStudyID(study.getIrbID());
       refreshTable();
       
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mptbl;
    private javax.swing.JComboBox patientComboBox;
    private javax.swing.JComboBox studyComboBox;
    // End of variables declaration//GEN-END:variables
}
