/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CRCAdminRole;

import Business.Organization.OncologyDepartment;
import Business.Stakeholders.studies;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shubh
 */
public class CRCAdminViewConsentPanel extends javax.swing.JPanel {

    /**
     * Creates new form siteadmin_workarea_managestudy_viewconsent
     */
//    public CRCAdminViewConsentPanel() {
//        initComponents();
//    }
    JPanel userProcessContainer;
    OncologyDepartment organization;
    studies study;

    CRCAdminViewConsentPanel(JPanel userProcessContainer, OncologyDepartment organization, studies study) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.study = study;
        
        cqv1TF.setText(study.getQuestion1());
                cqv2TF.setText(study.getQuestion2());
                cqv3TF.setText(study.getQuestion3());
                cqv4TF.setText(study.getQuestion4());
                                cqv5TF.setText(study.getQuestion5());
                                jLabel1.setText(organization.getName());

    }

    /**.setT
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cqv5TF = new javax.swing.JTextField();
        cqv4TF = new javax.swing.JTextField();
        cqv3TF = new javax.swing.JTextField();
        cqv2TF = new javax.swing.JTextField();
        cqv1TF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cqv5TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(cqv5TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 491, -1));

        cqv4TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(cqv4TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 491, -1));

        cqv3TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(cqv3TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 491, -1));

        cqv2TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(cqv2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 491, -1));

        cqv1TF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        cqv1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cqv1TFActionPerformed(evt);
            }
        });
        add(cqv1TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 491, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Question - 5:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 341, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Question - 4:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 286, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Question - 3:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 229, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Question - 2:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 174, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Question - 1:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 118, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("B & W Site Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(18, 51, 105));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 130, 50));

        jLabel4.setBackground(new java.awt.Color(18, 51, 105));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(2000, 1000));
        jLabel4.setMinimumSize(new java.awt.Dimension(2000, 1000));
        jLabel4.setPreferredSize(new java.awt.Dimension(2000, 1000));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cqv1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cqv1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cqv1TFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cqv1TF;
    private javax.swing.JTextField cqv2TF;
    private javax.swing.JTextField cqv3TF;
    private javax.swing.JTextField cqv4TF;
    private javax.swing.JTextField cqv5TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
